#!/bin/bash
clear
#make clean
make
#clear

#gdb --args enigma inputs/rotors/III.rot inputs/rotors/II.rot inputs/rotors/I.rot inputs/reflectors/II.rf


./enigma inputs/rotors/III.rot inputs/rotors/II.rot inputs/rotors/I.rot inputs/reflectors/II.rf inputs/plugboard/null.pb
